"""empty message

Revision ID: 787abbff6fa5
Revises: cee58225d470
Create Date: 2021-06-08 20:38:42.433600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787abbff6fa5'
down_revision = 'cee58225d470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
